### ISSUE TITLE
461ffe9 在 Android P 上崩溃

### ISSUE THREAD

**Issue by Love4Taylor** [Trumeet/MiPushFramework#100]
```
#######RuntimeEnvironmentInformation#######
crash time=2018-04-19 14:08:25.706
model=Pixel
android version=P(27)
brand=google
manufacturer=Google
board=sailfish
hardware=sailfish
device=sailfish
version name=0.3.3.r65.461ffe9-SNAPSHOT_framework
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=PPP1.180208.014
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: com.xiaomi.xmsf:pushservice, PID: 9581
java.lang.ExceptionInInitializerError
	at me.weishu.epic.art.Epic.hookMethod(Epic.java:87)
	at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:127)
	at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:181)
	at com.xiaomi.xmsf.push.hooks.impl.HookGetIsMIUI.fetchHook(HookGetIsMIUI.java:17)
	at com.xiaomi.xmsf.push.hooks.PushSdkHooks.getHooks(PushSdkHooks.java:34)
	at com.xiaomi.xmsf.XmsfApp.onCreate(XmsfApp.java:82)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5874)
	at android.app.ActivityThread.access$1100(ActivityThread.java:193)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.RuntimeException: Do not support this ARCH now!! API LEVEL:27
	at me.weishu.epic.art.Epic.<clinit>(Epic.java:77)
	... 16 more
```

**Comment by TimothyZhang023** [comment]
emmm ， sorry ， epic不支持 Android P， 我revert 了一下，P上禁用了所有hook。

Timer Hook还是改成手写了， 理论上应该没太大影响。
