### ISSUE TITLE
8215bab 的 Manager 在 Android P 上崩溃

### ISSUE THREAD

**Issue by Love4Taylor** [Trumeet/MiPushFramework#102]
已经按照 Releases 里面说的做了 先更新 manager 再更新 push...

```
#######RuntimeEnvironmentInformation#######
crash time=2018-04-21 16:23:00.229
model=Pixel
android version=P(27)
brand=google
manufacturer=Google
board=sailfish
hardware=sailfish
device=sailfish
version name=0.3.3.r73.8215bab-SNAPSHOT
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=PPP1.180208.014
#######ForceCloseCrashLog#######
FATAL EXCEPTION: AsyncTask #1
Process: top.trumeet.mipush, PID: 3900
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.xiaomi.xmsf/.push.control.ControlService }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1634)
	at android.app.ContextImpl.bindService(ContextImpl.java:1569)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:690)
	at top.trumeet.common.ipc.IPCUtils.connectService(IPCUtils.java:45)
	at top.trumeet.common.push.PushController.connect(PushController.java:47)
	at top.trumeet.common.push.PushController.getConnected(PushController.java:87)
	at top.trumeet.mipushframework.wizard.PushControllerWizardActivity$ConnectTask.doInBackground(PushControllerWizardActivity.java:107)
	at top.trumeet.mipushframework.wizard.PushControllerWizardActivity$ConnectTask.doInBackground(PushControllerWizardActivity.java:78)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Comment by keith-xiong** [comment]
FC+1

**Comment by moonheart** [comment]
卸载重装给了权限 仍然FC
```
#######RuntimeEnvironmentInformation#######
crash time=2018-04-22 00:27:16.148
model=Phh-Treble vanilla
android version=8.1.0(27)
brand=Android
manufacturer=unknown
board=msm8998
hardware=qcom
device=phhgsi_arm64_a
version name=0.3.3.r73.8215bab-SNAPSHOT
supported_abis=arm64-v8a & armeabi-v7a & armeabi
display=treble_arm64_avN-userdebug 8.1.0 OPM2.171019.029 180405 test-keys
#######ForceCloseCrashLog#######
FATAL EXCEPTION: AsyncTask #1
Process: top.trumeet.mipush, PID: 24163
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.xiaomi.xmsf/.push.control.ControlService }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1623)
	at android.app.ContextImpl.bindService(ContextImpl.java:1557)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
	at top.trumeet.common.ipc.IPCUtils.connectService(IPCUtils.java:45)
	at top.trumeet.common.push.PushController.connect(PushController.java:47)
	at top.trumeet.common.push.PushController.getConnected(PushController.java:87)
	at top.trumeet.mipushframework.MainActivity$ConnectTask.doInBackground(MainActivity.java:118)
	at top.trumeet.mipushframework.MainActivity$ConnectTask.doInBackground(MainActivity.java:107)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```

**Comment by kuroito** [comment]
我一开始也是如此，后来卸载了，先安装service，再安装manager就好了。。。

**Comment by moonheart** [comment]
@kuroito 感谢，可以使用了

**Comment by keith-xiong** [comment]
可是卸载重装的话，就算重新注册好多应用也会收不到通知
