### ISSUE TITLE
目前最新版(1d156a4) 点击详情里的应用会崩溃

### ISSUE THREAD

**Issue by w1324296014** [Trumeet/MiPushFramework#103]
小米推送服务管理器里，点击“应用”或“记录”两栏里的应用会立即崩溃。

**Comment by w1324296014** [comment]
以下是日志:
I/PushSdkHooks: init hook : HookGetIsMIUI
I/PushSdkHooks: init hook : HookPkgUninstallReceiver
I/PushSdkHooks: init hook : HookPingReceiver
I/PushSdkHooks: init hook : HookGetIsMIUI
I/PushSdkHooks: init hook : HookPkgUninstallReceiver
I/PushSdkHooks: init hook : HookPingReceiver
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:Registration, encryptAction:false, isRequest:false, pushAction:08 00 01 00 00 00 01 02 00 02 00 02 00 03 00 0B 00 04 00 00 01 3F 0C 00 02 0A 00 01 00 00 00 00 00 00 00 05 0B 00 02 00 00 00 0B 35 38 31 35 37 39 37 38 34 36 38 0B 00 03 00 00 00 0A 78 69 61 6F 6D 69 2E 63 6F 6D 0B 00 04 00 00 00 08 61 6E 41 31 62 6C 69 4C 08 00 06 00 00 00 00 00 0B 00 03 00 00 00 11 41 52 45 70 31 35 32 34 33 39 35 30 34 38 38 30 31 0B 00 04 00 00 00 07 31 30 30..., appid:1000271, packageName:com.xiaomi.xmsf, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:anA1bliL), metaInfo:PushMetaInfo(id:AREp1524395048801, messageTs:0))
I/MyMIPushMessageProcessor: receive a message, appid=1000271, msgid= AREp1524395048801
E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.xiaomi.slim.BlobWriter.write(Unknown Source)
	at com.xiaomi.slim.BlobWriter.shutdown(Unknown Source)
	at com.xiaomi.slim.SlimConnection.shutdown(Unknown Source)
	at com.xiaomi.smack.SocketConnection.disconnect(Unknown Source)
	at com.xiaomi.push.service.XMPushService.disconnect(Unknown Source)
	at com.xiaomi.smack.SocketConnection$2.process(Unknown Source)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

W/XMPushService Bridge: Denied register request: com.tencent.tim
E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.xiaomi.slim.BlobWriter.write(Unknown Source)
	at com.xiaomi.slim.BlobWriter.shutdown(Unknown Source)
	at com.xiaomi.slim.SlimConnection.shutdown(Unknown Source)
	at com.xiaomi.smack.SocketConnection.disconnect(Unknown Source)
	at com.xiaomi.push.service.XMPushService.disconnect(Unknown Source)
	at com.xiaomi.smack.SocketConnection$2.process(Unknown Source)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.xiaomi.slim.BlobWriter.write(Unknown Source)
	at com.xiaomi.slim.BlobWriter.shutdown(Unknown Source)
	at com.xiaomi.slim.SlimConnection.shutdown(Unknown Source)
	at com.xiaomi.smack.SocketConnection.disconnect(Unknown Source)
	at com.xiaomi.push.service.XMPushService.disconnect(Unknown Source)
	at com.xiaomi.smack.SocketConnection$2.process(Unknown Source)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

I/PushSdkHooks: init hook : HookGetIsMIUI
I/PushSdkHooks: init hook : HookPkgUninstallReceiver
I/PushSdkHooks: init hook : HookPingReceiver
I/PushSdkHooks: init hook : HookGetIsMIUI
I/PushSdkHooks: init hook : HookPkgUninstallReceiver
I/PushSdkHooks: init hook : HookPingReceiver
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:Notification, encryptAction:false, isRequest:true, pushAction:08 00 01 00 00 00 09 02 00 02 00 02 00 03 01 0B 00 04 00 00 02 9B 0C 00 02 0A 00 01 00 00 00 00 00 00 00 05 0B 00 02 00 00 00 0B 35 38 31 35 37 39 37 38 34 36 38 0B 00 03 00 00 00 0A 78 69 61 6F 6D 69 2E 63 6F 6D 0B 00 04 00 00 00 08 61 6E 41 31 62 6C 69 4C 08 00 06 00 00 00 00 00 0B 00 03 00 00 00 11 39 39 76 68 31 35 32 34 34 30 30 32 30 36 32 31 32 0B 00 04 00 00 00 07 31 30 30..., appid:1000271, packageName:com.xiaomi.xmsf, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:anA1bliL), metaInfo:PushMetaInfo(id:99vh1524400206212, messageTs:0))
I/MyMIPushMessageProcessor: receive a message, appid=1000271, msgid= 99vh1524400206212
I/MyClientEventDispatcher: buildContainer: XmPushActionContainer(action:UnRegistration, encryptAction:false, isRequest:false, pushAction:08 00 01 00 00 00 02 02 00 02 00 02 00 03 00 0B 00 04 00 00 00 9B 0C 00 02 0A 00 01 00 00 00 00 00 00 00 05 0B 00 02 00 00 00 0B 35 38 31 35 37 39 37 38 34 36 38 0B 00 03 00 00 00 0A 78 69 61 6F 6D 69 2E 63 6F 6D 0B 00 04 00 00 00 08 61 6E 41 31 62 6C 69 4C 08 00 06 00 00 00 00 00 0B 00 03 00 00 00 11 6E 30 53 41 31 35 32 34 34 30 30 32 30 36 34 32 31 0B 00 04 00 00 00 07 31 30 30..., appid:1000271, packageName:com.xiaomi.xmsf, target:Target(channelId:5, userId:58157978468, server:xiaomi.com, resource:anA1bliL), metaInfo:PushMetaInfo(id:n0SA1524400206421, messageTs:0))
I/MyMIPushMessageProcessor: receive a message, appid=1000271, msgid= n0SA1524400206421
E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.xiaomi.slim.BlobWriter.write(Unknown Source)
	at com.xiaomi.slim.BlobWriter.shutdown(Unknown Source)
	at com.xiaomi.slim.SlimConnection.shutdown(Unknown Source)
	at com.xiaomi.smack.SocketConnection.disconnect(Unknown Source)
	at com.xiaomi.push.service.XMPushService.disconnect(Unknown Source)
	at com.xiaomi.smack.SocketConnection$2.process(Unknown Source)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.xiaomi.slim.BlobWriter.write(Unknown Source)
	at com.xiaomi.slim.BlobWriter.shutdown(Unknown Source)
	at com.xiaomi.slim.SlimConnection.shutdown(Unknown Source)
	at com.xiaomi.smack.SocketConnection.disconnect(Unknown Source)
	at com.xiaomi.push.service.XMPushService.disconnect(Unknown Source)
	at com.xiaomi.smack.SocketConnection$2.process(Unknown Source)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

W/XMPushService Bridge: Don't register multi request tv.danmaku.bili
W/XMPushService Bridge: Don't register multi request tv.danmaku.bili
W/XMPushService Bridge: Don't register multi request tv.danmaku.bili
W/XMPushService Bridge: Don't register multi request tv.danmaku.bili
W/XMPushService Bridge: Don't register multi request tv.danmaku.bili
E/PushCore: 
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStre
