### ISSUE TITLE
闪退啊，新版的权限是干什么的，很必要吗

### ISSUE THREAD

**Issue by keith-xiong** [Trumeet/MiPushFramework#105]
旧版没这权限不是好好的吗，为什么要加这权限呢？
刚升级时manager界面都打不开就闪退，看日志是权限问题，手动给了权限还是闪退，没办法取消了应用管理器激活，重启后manager界面能打开，但是点应用条目就闪退，日志显示权限为空。看来我这手机是获取不到这权限了，只能停留在旧版了🙁

> Process: top.trumeet.mipush
Flags: 0x3888bec5
Package: top.trumeet.mipush v78 (0.3.3.r78.1d156a4-SNAPSHOT)
Build: nubia/NX569J/NX569J:6.0.1/MMB29M/nubia09261336:user/release-keys

java.lang.RuntimeException: Unable to start activity ComponentInfo{top.trumeet.mipush/top.trumeet.mipushframework.permissions.ManagePermissionsActivity}: java.lang.NullPointerException: permission cannot be null or empty
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2573)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2633)
	at android.app.ActivityThread.access$900(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:171)
	at android.app.ActivityThread.main(ActivityThread.java:5682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: permission cannot be null or empty
	at android.content.pm.PackageManager.buildRequestPermissionsIntent(PackageManager.java:2628)
	at android.app.Activity.requestPermissions(Activity.java:3874)
	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:479)
	at top.trumeet.common.utils.PermissionUtils.requestPermissions(PermissionUtils.java:31)
	at top.trumeet.common.utils.PermissionUtils.requestPermissionsIfNeeded(PermissionUtils.java:69)
	at top.trumeet.mipushframework.permissions.ManagePermissionsActivity.onCreate(ManagePermissionsActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:6320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2526)
	... 10 more

**Comment by TimothyZhang023** [comment]
试试最新版本
