### ISSUE TITLE
18bc05b-SNAPSHOT 点击应用进入详情时闪退

### ISSUE THREAD

**Issue by ShadowLyin** [Trumeet/MiPushFramework#109]
日志如下
```
E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isMIUI(Unknown Source:4)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetIMEI(Unknown Source:8)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:642)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isNotMIUI(Unknown Source:3)
	at com.xiaomi.mipush.sdk.MiPushClient.getDefaultSwitch(Unknown Source:0)
	at com.xiaomi.mipush.sdk.MiPushClient.loadPlugin(Unknown Source:12)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:388)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

W/XMPushService Bridge: Don't register multi request com.zhihu.android
W/XMPushService Bridge: Don't register multi request com.zhihu.android
W/XMPushService Bridge: Don't register multi request com.zhihu.android
W/XMPushService Bridge: Don't register multi request com.zhihu.android
W/XMPushService Bridge: Don't register multi request com.zhihu.android
```

**Comment by TimothyZhang023** [comment]
APP界面还是通知？

**Comment by ShadowLyin** [comment]
@TimothyZhang023 都有

**Comment by TimothyZhang023** [comment]
升级到最新版本。

crash可能是权限问题，
这个是push日志无影响
