### ISSUE TITLE
无法进入主界面了←_←

### ISSUE THREAD

**Issue by naloder** [Trumeet/MiPushFramework#112]
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: Not allowed to bind to service Intent { cmp=com.xiaomi.xmsf/.push.control.ControlService }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1965)
	at android.app.ContextImpl.bindService(ContextImpl.java:1929)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.content.ContextWrapper.bindService(<Xposed>)
	at top.trumeet.common.ipc.IPCUtils.connectService(IPCUtils.java:45)
	at top.trumeet.common.push.PushController.connect(PushController.java:47)
	at top.trumeet.common.push.PushController.getConnected(PushController.java:87)
	at top.trumeet.mipushframework.wizard.PushControllerWizardActivity$ConnectTask.doInBackground(PushControllerWizardActivity.java:112)
	at top.trumeet.mipushframework.wizard.PushControllerWizardActivity$ConnectTask.doInBackground(PushControllerWizardActivity.java:80)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by TimothyZhang023** [comment]
把push和app都升级到最新版，，
最好是先安装push
