### ISSUE TITLE
get isMIUI failed log

### ISSUE THREAD

**Issue by youppgd** [Trumeet/MiPushFramework#116]
W/XMPushService Bridge: Don't register multi request com.tencent.pb
E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isMIUI(Unknown Source:4)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetIMEI(Unknown Source:8)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:642)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isMIUI(Unknown Source:4)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetIMEI(Unknown Source:8)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetSubIMEI(Unknown Source:39)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:670)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isNotMIUI(Unknown Source:3)
	at com.xiaomi.mipush.sdk.MiPushClient.getDefaultSwitch(Unknown Source:0)
	at com.xiaomi.mipush.sdk.MiPushClient.loadPlugin(Unknown Source:12)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:388)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

**Comment by TimothyZhang023** [comment]
文件没权限，理论上，我们应该hook了这个函数。。。

应该是一加系统吧。
理论上没有影响，如果强迫症的话，自己加上 三个组的读权限就行。。

**Comment by heinzan** [comment]
1+++
