### ISSUE TITLE
pixel原生8.0系统正式版无法获取日志

### ISSUE THREAD

**Issue by antinomypa** [Trumeet/MiPushFramework#12]
ROM：pixel原生8.0系统正式版
未安装绿色守护，黑域，未root，无xposed

问题：所有应用都无法收到，点按修复失败，点击获取日志发生FC，可复现

**Comment by Trumeet** [comment]
fc日志？

**Comment by antinomypa** [comment]
08-28 20:31:00.041   910  2403 I OpenGLRenderer: Initialized EGL, version 1.4
08-28 20:31:00.041   910  2403 D OpenGLRenderer: Swap behavior 2
08-28 20:31:00.483   910   952 W ActivityManager: Activity pause timeout for ActivityRecord{980095e u0 com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity t15306 f}
08-28 20:31:00.562  4240  4240 W SessionLifecycleManager: Handover failed. Creating new session controller.
08-28 20:31:00.565   488   488 D SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
08-28 20:31:00.574  4240 22876 W Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-28 20:31:00.579  4240 27241 W Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-28 20:31:00.626  4240  4240 I MicroDetectionState: Keep running DSP hotword
08-28 20:31:00.634  4240 24292 W Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
08-28 20:31:00.819  4240  4240 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
08-28 20:31:00.820  4240  4240 I chatty  : uid=10048(u0_a48) com.google.android.googlequicksearchbox:search identical 2 lines
08-28 20:31:00.821  4240  4240 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
08-28 20:31:00.894 20117 20132 D MSF.D.QLog: QLog clear logs
08-28 20:31:00.952   910   952 I ActivityManager: Killing 31645:com.tencent.mm:appbrand0/u0a189 (adj 906): empty #17
08-28 20:31:01.095 26064 26089 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-28 20:31:01.095 26064 26089 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-28 20:31:01.301   910   920 I zygote64: NativeAllocBackground concurrent copying GC freed 40278(2034KB) AllocSpace objects, 6(120KB) LOS objects, 42% free, 31MB/54MB, paused 363us total 202.542ms
08-28 20:31:05.637   910   952 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } to tv.danmaku.bili/com.bilibili.bilibililive.im.abroad.KeepAliveAlarmReciver
08-28 20:31:10.955   910   952 W ActivityManager: Activity destroy timeout for ActivityRecord{980095e u0 com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity t15306 f}
08-28 20:31:12.718 15137 16501 I PlayCommon: [8822] com.google.android.play.a.g.e(244): Preparing logs for uploading
08-28 20:31:12.719 15137 16501 I PlayCommon: [8822] com.google.android.play.a.g.e(248): No file ready to send
08-28 20:31:13.196   910 16810 I ActivityManager: Killing 32442:com.xiaomi.xmsf/u0a487 (adj 902): crash
08-28 20:31:13.236   910   981 W ActivityManager: setHasOverlayUi called on unknown pid: 32442
08-28 20:31:13.400   910  1169 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
08-28 20:31:13.881 20155 20181 D MSF.D.QLog: QLog clear logs
08-28 20:31:14.621   910 16810 W ContextHubService: Sending msg of type 0 len 10 to app 476f6f676c00100b on hub 0
08-28 20:31:14.622   656   656 I ContextHubHalAdapter: Sending msg of type 0, size 10 to app 0x476f6f676c00100b
08-28 20:31:14.633   910  1208 D ContextHubService: Sending message 1025 version 0 from hubHandle 0, appInstance 15, callBackCount 1
08-28 20:31:14.687 13328 13328 I ActivityUpsampling: Received intent
08-28 20:31:14.687 13328 13328 I ActivityUpsampling: Initialize ActivityUpsamplingManager
08-28 20:31:14.702 13328 13328 I ActivityUpsampling: ActivityUpsamplingReceiver received intent
08-28 20:31:14.741 13328 32485 I ActivityUpsampling: AR upsampling state transition NORMAL_STATE --> NORMAL_STATE, activity: unknown
08-28 20:31:14.772 13328 32485 I Fit:LocationProvider: Stopping the high fidelity fg service
08-28 20:31:14.777 13328 32485 I Fit:LocationProvider: Location recording changed to : STOP_HIGH_FIDELITY_RECORDING.
08-28 20:31:14.777 13328 32485 I ActivityUpsampling: Recording event
08-28 20:31:14.888 13328 32485 I ActivityUpsampling: Autodetect event inserted: DataPoint{[1, 4]@[0, 1503923474777000000,raw=0,insert=0](r:android.apps.fitness.autodetect.event:com.google.android.apps.fitness:autodetect_events N/A)}
08-28 20:31:14.888  2068 10931 E ActivityThread: Failed to find provider info for com.google.android.wearable.settings
08-28 20:31:14.894 13328 32485 I ActivityUpsampling: Finishing async work
08-28 20:31:14.910   910  3415 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } to tv.danmaku.bili/com.bilibili.bilibililive.im.abroad.KeepAliveAlarmReciver
08-28 20:31:15.909 20117 20132 D MSF.D.QLog: QLog clear logs
08-28 20:31:17.566   910 16810 D WificondControl: Scan result ready event
08-28 20:31:17.889   910   952 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } to tv.danmaku.bili/com.bilibili.bilibililive.im.abroad.KeepAliveAlarmReciver
08-28 20:31:24.781 25303 25303 D  arw    : -1000
08-28 20:31:24.781 25303 25303 I  arw    : what:-1000
08-28 20:31:27.052   670   670 E hw-IPCThreadState: binder thread pool (1 threads) starved for 101 ms
08-28 20:31:28.890 20155 20181 D MSF.D.QLog: QLog clear logs
08-28 20:31:30.721   910  3415 W ContextHubService: Sending msg of type 0 len 10 to app 476f6f676c00100b on hub 0
08-28 20:31:30.724   656   656 I ContextHubHalAdapter: Sending msg of type 0, size 10 to app 0x476f6f676c00100b
08-28 20:31:30.739   910  1208 D ContextHubService: Sending message 1025 version 0 from hubHandle 0, appInstance 15, callBackCount 1
08-28 20:31:30.850 13328 13328 I ActivityUpsampling: Received intent
08-28 20:31:30.850 13328 13328 I ActivityUpsampling: Initialize ActivityUpsamplingManager
08-28 20:31:30.886 13328 13328 I ActivityUpsampling: ActivityUpsamplingReceiver received intent
08-28 20:31:30.919 13328 32489 I ActivityUpsampling: AR upsampling state transition NORMAL_STATE --> NORMAL_STATE, activity: unknown
08-28 20:31:30.924 20117 20132 D MSF.D.QLog: QLog clear logs
08-28 20:31:30.951 13328 32489 I Fit:LocationProvider: Stopping the high fidelity fg service
08-28 20:31:30.954 13328 32489 I Fit:LocationProvider: Location recording changed to : STOP_HIGH_FIDELITY_RECORDING.
08-28 20:31:30.954 13328 32489 I ActivityUpsampling: Recording event
08-28 20:31:31.077 13328 32489 I ActivityUpsampling: Autodetect event inserted: DataPoint{[1, 4]@[0, 1503923490954000000,raw=0,insert=0](r:android.apps.fitness.autodetect.event:com.google.android.apps.fitness:autodetect_events N/A)}
08-28 20:31:31.080  2068 10931 E ActivityThread: Failed to find provider info for com.google.android.wearable.settings
08-28 20:31:31.085 13328 32489 I ActivityUpsampling: Finishing async work

不太清楚哪部分有用，所以复制了一段时间内的

**Comment by Trumeet** [comment]
遗憾地告诉你啊.. 都没用（
Level 调 error，清空日志，崩溃后把日志给我

**Comment by antinomypa** [comment]
08-28 20:48:19.243  2493  2493 E AndroidRuntime: FATAL EXCEPTION: main
08-28 20:48:19.243  2493  2493 E AndroidRuntime: Process: com.xiaomi.xmsf, PID: 2493
08-28 20:48:19.243  2493  2493 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://top.trumeet.mipushframework.fileprovider/logs/file.log typ=application/octet-stream flg=0x1 }
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1936)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4472)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.support.v4.a.f.startActivityForResult(Unknown Source:10)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.support.v4.a.j.startActivityForResult(Unknown Source:0)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4430)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.support.v4.a.j.startActivityForResult(Unknown Source:10)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4791)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:4759)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at top.trumeet.mipushframework.b.a.b(Unknown Source:65)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at top.trumeet.mipushframework.settings.a$1.a(Unknown Source:6)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at moe.shizuku.preference.Preference.F(Unknown Source:16)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at moe.shizuku.preference.Preference.a(Unknown Source:0)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at moe.shizuku.preference.Preference$1.onClick(Unknown Source:2)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.view.View.performClick(View.java:6256)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24697)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6541)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-28 20:48:19.243  2493  2493 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-28 20:48:20.365  2068  2068 E ctxmgr  : [PlaceFenceHelper]NearbyBuffer is null!
08-28 20:48:20.417  2068 28804 E ActivityThread: Failed to find provider info for com.google.android.wearable.settings
08-28 20:48:20.576  2068  3311 E ActivityThread: Failed to find provider info for com.google.android.wearable.settings

**Comment by lanbingxuanyi** [comment]
一加3T 同样问题 点击获取日志FC
08-28 21:43:54.148 E/cnss-daemon(804): Stale or unreachable neighbors, ndm state: 16
08-28 21:43:54.748 E/ActivityManager(1428): applyOptionsLocked: Unknown animationType=0
08-28 21:43:55.444 E/OnePlusAppBootManager(1428): # startActivityLocked # aInfo = null
08-28 21:43:55.446 E/AndroidRuntime(6161): FATAL EXCEPTION: main
08-28 21:43:55.446 E/AndroidRuntime(6161): Process: com.xiaomi.xmsf, PID: 6161
08-28 21:43:55.446 E/AndroidRuntime(6161): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://top.trumeet.mipushframework.fileprovider/logs/file.log typ=application/octet-stream flg=0x1 }
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1987)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1696)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Activity.startActivityForResult(Activity.java:4291)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.support.v4.a.f.startActivityForResult(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.support.v4.a.j.startActivityForResult(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Activity.startActivityForResult(Activity.java:4249)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.support.v4.a.j.startActivityForResult(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Activity.startActivity(Activity.java:4603)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.Activity.startActivity(Activity.java:4563)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at top.trumeet.mipushframework.b.a.b(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at top.trumeet.mipushframework.settings.a$1.a(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at moe.shizuku.preference.Preference.F(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at moe.shizuku.preference.Preference.a(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at moe.shizuku.preference.Preference$1.onClick(Unknown Source)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.view.View.performClick(View.java:5669)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.view.View$PerformClick.run(View.java:22549)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.os.Handler.handleCallback(Handler.java:751)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.os.Looper.loop(Looper.java:154)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at android.app.ActivityThread.main(ActivityThread.java:6369)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at java.lang.reflect.Method.invoke(Native Method)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-28 21:43:55.446 E/AndroidRuntime(6161): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-28 21:43:55.466 E/lowmemorykiller(578): Error writing /proc/6161/oom_score_adj; errno=22
08-28 21:43:55.499 E/InputDispatcher(1428): channel 'f1bd66a com.xiaomi.xmsf/top.trumeet.mipushframework.settings.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-28 21:43:56.571 E/LockboxBrokerService(2645): Could not query UDC's getDeviceDataUploadOptInStatus; 15 null
08-28 21:43:57.524 D/NetworkController.MobileSignalController(1)( 1909): onSignalStrengthsChanged signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 29 -85 -8 66 2147483647 2147483647 4 4 gsm|lte level=4 voicelevel=4 datalevel=4
08-28 21:43:57.531 I/NetworkController.MobileSignalController(1)( 1909):  showDisableIcon:false
08-28 21:43:57.538 D/NetworkController.MobileSignalController(1)( 1909): getSlotProvisionStatus slotId: 0, status = 1
08-28 21:43:57.643 E/ActivityManager(1428): applyOptionsLocked: Unknown animationType=0
08-28 21:43:59.105 E/IzatSvc_Wiper(1428): W/Num of elements returned by LOWI 4

**Comment by flyfei** [comment]
这么快就开始测试 8.0 了？昨晚刚收到系统8.0更新

**Comment by flyfei** [comment]
这么快就开始测试 8.0 了？昨晚刚收到系统8.0更新
