### ISSUE TITLE
软件内显示收到推送，但是通知栏没有弹出通知

### ISSUE THREAD

**Issue by ddggh5566** [Trumeet/MiPushFramework#13]
[日志.txt](https://github.com/Trumeet/MiPushFramework/files/1256812/default.txt)

**Comment by TimothyZhang023** [comment]
日志是没用的 @Trumeet  
异常发生在 com\xiaomi\push\service\MyClientEventDispatcher.java 

`

        private static void doProcessMIPushMessage(XMPushService var0, byte[] var1, long var2) {
            try {
                Method method = MIPushEventProcessor.class.getDeclaredMethod("processMIPushMessage"
                        , XMPushService.class,
                        byte[].class, long.class);
                method.setAccessible(true);
                method.invoke(null, var0, var1, var2);
            } catch (Exception e) {
这里没有记录日志！
                 throw new RuntimeException(e);
            }
        }

`


加上日志之后异常栈信息如下 


`java.lang.NoSuchFieldException: No field extraNotification in class Landroid/app/Notification; (declaration of 'android.app.Notification' appears in /system/framework/framework.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.xiaomi.push.service.MIPushNotificationHelper.setTargetPackage(Unknown Source:5)
	at com.xiaomi.push.service.MIPushNotificationHelper.notifyPushMessage(Unknown Source:256)
	at com.xiaomi.push.service.MIPushEventProcessor.postProcessMIPushMessage(Unknown Source:350)
	at com.xiaomi.push.service.MIPushEventProcessor.processMIPushMessage(Unknown Source:555)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.doProcessMIPushMessage(MyClientEventDispatcher.java:177)
	at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.runProcessMIPushMessage(MyClientEventDispatcher.java:165)
	at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.processNewPacket(MyClientEventDispatcher.java:186)
	at com.xiaomi.push.service.ClientEventDispatcher.notifyPacketArrival(Unknown Source:48)
	at com.xiaomi.push.service.MyClientEventDispatcher.notifyPacketArrival(MyClientEventDispatcher.java:82)
	at com.xiaomi.push.service.PacketSync.handleBlob(Unknown Source:51)
	at com.xiaomi.push.service.PacketSync.onBlobReceive(Unknown Source:10)
	at com.xiaomi.push.service.XMPushService$BlobReceiveJob.process(Unknown Source:8)
	at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source:38)
	at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source:175)
`

**Comment by TimothyZhang023** [comment]
`
  String str1;
      if (localPushMetaInfo.getExtra() == null)
      {
        str1 = null;
        if ((!MIUIUtils.isMIUI()) || (str1 == null)) {}
      }
      try
      {
        int m = Integer.parseInt(str1);
        setMessageCount(localNotification, m);
        if ("com.xiaomi.xmsf".equals(paramContext.getPackageName()))
        {
          String str2 = getTargetPackage(paramXmPushActionContainer);
          setTargetPackage(localNotification, str2);
        }
`


这里我们可以 

`XmPushActionContainer xmPushActionContainer = buildContainer(var1);
                xmPushActionContainer.getMetaInfo().setExtra(null);
                var1 = XmPushThriftSerializeUtils.convertThriftObjectToBytes(xmPushActionContainer);`

就可以跳过那段。

然后System UI不停的crash。。

**Comment by TimothyZhang023** [comment]
fixed
