### ISSUE TITLE
点击通知后报错

### ISSUE THREAD

**Issue by Minelu** [Trumeet/MiPushFramework#130]
错误如下，Android 8.1 红米5p，版本 0787a97 - SNAPSHOT

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:881)
	at android.app.ContextImpl.startActivity(ContextImpl.java:855)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:372)
	at com.xiaomi.helper.impl.ActivityUsageStatsImpl.guideToEnable(ActivityUsageStatsImpl.java:42)
	at com.xiaomi.push.sdk.MyPushMessageHandler.onHandleIntent(MyPushMessageHandler.java:44)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by TimothyZhang023** [comment]
Android 8.1  具体rom

**Comment by Minelu** [comment]
@TimothyZhang023 crDroid 4.3 取消激活xposed后又好了

**Comment by TimothyZhang023** [comment]
@Minelu mi 这个和xposed没关系。guideToEnable把权限给了就不会触发

**Comment by TimothyZhang023** [comment]
fixed in latest build
