### ISSUE TITLE
push crashed

### ISSUE THREAD

**Issue by shibeta** [Trumeet/MiPushFramework#153]
华为m3，emui5.1 Android n，刚才在用gmail时一直这样
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at com.xiaomi.helper.DetectionService.onAccessibilityEvent(DetectionService.java:35)
	at android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1449)
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1585)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6595)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by TimothyZhang023** [comment]
辅助模式这里处理有问题，可以切成 使用情况API 那个么

**Comment by TimothyZhang023** [comment]
fixed at  #99b41ad

**Comment by shibeta** [comment]
谢谢
