### ISSUE TITLE
Android 7.1.2 升级后打开闪退

### ISSUE THREAD

**Issue by StarWishsama** [Trumeet/MiPushFramework#218]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
升级至1130版本后，小米推送服务打开闪退

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 正常打开小米推送服务
2. 弹出“小米推送服务已停止运行”

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
应当正常打开小米推送服务。

**Screenshots**（截图）
[https://i.loli.net/2018/12/01/5c024fdea2c86.png](url)

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setEnabled(boolean)' on a null object reference
	at top.trumeet.mipushframework.MainFragment.refreshStatus(MainFragment.java:198)
	at top.trumeet.mipushframework.MainFragment.onChange(MainFragment.java:213)
	at top.trumeet.mipushframework.MainActivity$ConnectTask$1.onReady(MainActivity.java:171)
	at top.trumeet.common.push.ControllerImpl$$Lambda$0.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Lineage OS
 - Android Version: 7.1.2
 - Version 0.3.6.20181130.7881203

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by Trumeet** [comment]
非常感谢，您提供的信息至关重要，我们会分析并修复它。

**Comment by StarWishsama** [comment]
更新系统后竟然没闪退了（

**Comment by Trumeet** [comment]
?!

**Comment by Trumeet** [comment]
那先不管了...（逃
