### ISSUE TITLE
Android P 注册异常

### ISSUE THREAD

**Issue by singleNeuron** [Trumeet/MiPushFramework#248]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）

在Android P上，所有应用全部注册异常，第一次使用push，没有清除过数据

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 安装了manager和push
2. 安装magsik的riru模块并重启
3. 打开任意一个使用mipush的软件

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）
似乎在AndroidO以上，系统阻止了非root用户直接读取/system/build.prop，关于这一点在Google上有很多相关的讨论。

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）
没有必要上传，所有的日志都在重复反应这一个问题
> E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isMIUI(Unknown Source:4)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetIMEI(Unknown Source:8)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:642)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Statix OS
 - Android Version: 9
 - Version: 0.3.6

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by singleNeuron** [comment]
是我沙雕，开了流量节省程序

**Comment by heinzan** [comment]
how solved this error?

**Comment by singleNeuron** [comment]
> how solved this error?

我关闭了流量节省程序并将框架和push加入不限制后台流量白名单
I'm sorry that my English is too poor to express it, you may need to use a translator

**Comment by heinzan** [comment]
> > how solved this error?
> 
> 我关闭了流量节省程序并将框架和push加入不限制后台流量白名单
> I'm sorry that my English is too poor to express it, you may need to use a translator

got it
