### ISSUE TITLE
[TODO] 一个可能导致无法收到通知的原因

### ISSUE THREAD

**Issue by Trumeet** [Trumeet/MiPushFramework#33]
根据收到 **通知**（而不是 **透传**）的 logs 看，在发送通知的时候出现了异常：
```
Meet exception when call Method 'setGroup' in android.app.Notification$Builder@e8aa112
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
                                                                            at java.lang.Class.isAssignableFrom(Class.java:545)
                                                                            at com.xiaomi.channel.commonutils.reflect.JavaCalls.compareClassLists(Unknown Source)
                                                                            at com.xiaomi.channel.commonutils.reflect.JavaCalls.findMethodByName(Unknown Source)
                                                                            at com.xiaomi.channel.commonutils.reflect.JavaCalls.getDeclaredMethod(Unknown Source)
                                                                            at com.xiaomi.channel.commonutils.reflect.JavaCalls.callMethodOrThrow(Unknown Source)
                                                                            at com.xiaomi.channel.commonutils.reflect.JavaCalls.callMethod(Unknown Source)
                                                                            at com.xiaomi.push.service.MIPushNotificationHelper.getNotificationForLargeIcons(Unknown Source)
                                                                            at com.xiaomi.push.service.MIPushNotificationHelper.notifyPushMessage(Unknown Source)
                                                                            at com.xiaomi.push.service.MIPushEventProcessor.postProcessMIPushMessage(Unknown Source)
                                                                            at com.xiaomi.push.service.MIPushEventProcessor.processMIPushMessage(Unknown Source)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.doProcessMIPushMessage(MyClientEventDispatcher.java:131)
                                                                            at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.runProcessMIPushMessage(MyClientEventDispatcher.java:119)
                                                                            at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.processNewPacket(MyClientEventDispatcher.java:140)
                                                                            at com.xiaomi.push.service.ClientEventDispatcher.notifyPacketArrival(Unknown Source)
                                                                            at com.xiaomi.push.service.MyClientEventDispatcher.notifyPacketArrival(MyClientEventDispatcher.java:76)
                                                                            at com.xiaomi.push.service.PacketSync.handleBlob(Unknown Source)
                                                                            at com.xiaomi.push.service.PacketSync.onBlobReceive(Unknown Source)
                                                                            at com.xiaomi.push.service.XMPushService$BlobReceiveJob.process(Unknown Source)
                                                                            at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
                                                                            at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)
```
小米推送在 API 24 及以上将使用 `Builder#setGroup`。（但是不知道为什么用的反射），然后就崩掉了。

之后通知就会无法 notify，后面没有分析 `MIPushEventProcessor` 的代码，很可能里面 crash 之后就转 broadcast 了。（我这里是这样）

然后应用就会收到 broadcast 而不是通知。

**Comment by Trumeet** [comment]
还是不知道为什么要反射，`setGroup` 并不是 `@hide` 的呀..

**Comment by Trumeet** [comment]
刚写了个测试，并没有发现什么问题（
```java
Notification.Builder builder
                = new Notification.Builder(InstrumentationRegistry.getTargetContext());
        JavaCalls.callMethod(builder, "setGroup", "2333");
        JavaCalls.callMethod(builder, "setGroupSummary", true);
```

**Comment by Trumeet** [comment]
还有个错：
```java
java.lang.NoSuchFieldException: No field extraNotification in class Landroid/app/Notification; (declaration of 'android.app.Notification' appears in /system/framework/framework.jar)
                                                                           at java.lang.Class.getDeclaredField(Native Method)
                                                                           at com.xiaomi.push.service.MIPushNotificationHelper.setTargetPackage(Unknown Source)
                                                                           at com.xiaomi.push.service.MIPushNotificationHelper.notifyPushMessage(Unknown Source)
                                                                           at com.xiaomi.push.service.MIPushEventProcessor.postProcessMIPushMessage(Unknown Source)
                                                                           at com.xiaomi.push.service.MIPushEventProcessor.processMIPushMessage(Unknown Source)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.doProcessMIPushMessage(MyClientEventDispatcher.java:112)
                                                                           at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.runProcessMIPushMessage(MyClientEventDispatcher.java:100)
                                                                           at com.xiaomi.push.service.MyClientEventDispatcher$EventProcessor.processNewPacket(MyClientEventDispatcher.java:121)
                                                                           at com.xiaomi.push.service.ClientEventDispatcher.notifyPacketArrival(Unknown Source)
                                                                           at com.xiaomi.push.service.MyClientEventDispatcher.notifyPacketArrival(MyClientEventDispatcher.java:58)
                                                                           at com.xiaomi.push.service.PacketSync.handleBlob(Unknown Source)
                                                                           at com.xiaomi.push.service.PacketSync.onBlobReceive(Unknown Source)
                                                                           at com.xiaomi.push.service.XMPushService$BlobReceiveJob.process(Unknown Source)
                                                                           at com.xiaomi.push.service.XMPushService$Job.run(Unknown Source)
                                                                           at com.xiaomi.push.service.JobScheduler$SchedulerImpl.run(Unknown Source)

```

**Comment by Trumeet** [comment]
又看了一下，`JavaCalls#callMethod` 和 `MIPushNotificationHelper#setTargetPackage` 崩掉之后会 catch..（

**Comment by wanxsb** [comment]
我这也有这个问题
