### ISSUE TITLE
偶发性触发crash

### ISSUE THREAD

**Issue by naloder** [Trumeet/MiPushFramework#54]
java.lang.RuntimeException: Unable to start receiver com.xiaomi.xmsf.push.service.receivers.AccountChangedReceiver: java.lang.SecurityException: caller uid 10612 lacks any of android.permission.GET_ACCOUNTS
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3059)
	at android.app.ActivityThread.access$1800(ActivityThread.java:189)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.SecurityException: caller uid 10612 lacks any of android.permission.GET_ACCOUNTS
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.accounts.IAccountManager$Stub$Proxy.getAccounts(IAccountManager.java:728)
	at android.accounts.AccountManager.getAccounts(AccountManager.java:407)
	at com.xiaomi.xmsf.push.service.Utils.getXiaomiUserId(Utils.java:15)
	at com.xiaomi.xmsf.push.service.XMAccountManager.setAccountAsAlias(XMAccountManager.java:29)
	at com.xiaomi.xmsf.push.service.receivers.AccountChangedReceiver.onReceive(AccountChangedReceiver.java:13)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3044)
	... 10 more

**Comment by TimothyZhang023** [comment]
这个我也看到了，看上去就是缺少权限，MiPushClient注册的时候
