### ISSUE TITLE
最新snapshot导致系统界面不停重启

### ISSUE THREAD

**Issue by TimothyZhang023** [Trumeet/MiPushFramework#74]
状况和上次那个system ui crash差不多
还没抓到异常栈。感觉还是icon的问题。

**Comment by TimothyZhang023** [comment]
触发的好像是coolapk的feedlike消息

**Comment by TimothyZhang023** [comment]
```
02-24 16:50:54.993 10514 10514 D AndroidRuntime: Shutting down VM
02-24 16:50:54.994 10514 10514 E AndroidRuntime: FATAL EXCEPTION: main
02-24 16:50:54.994 10514 10514 E AndroidRuntime: Process: com.android.systemui, PID: 10514
02-24 16:50:54.994 10514 10514 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1001)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:968)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:918)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.updateMaskBoundsInternal(AdaptiveIconDrawable.java:333)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.updateLayerBounds(AdaptiveIconDrawable.java:295)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.drawable.AdaptiveIconDrawable.onStateChange(AdaptiveIconDrawable.java:782)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.graphics.drawable.Drawable.setState(Drawable.java:775)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.widget.ImageView.drawableStateChanged(ImageView.java:1305)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.view.View.refreshDrawableState(View.java:20118)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:17515)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:4959)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:4750)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.NotificationIconAreaController.updateIconsForLayout(NotificationIconAreaController.java:274)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.NotificationIconAreaController.updateNotificationIcons(NotificationIconAreaController.java:182)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.updateNotificationShade(StatusBar.java:2213)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.updateNotifications(StatusBar.java:2516)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.addNotificationViews(StatusBar.java:7634)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.addEntry(StatusBar.java:1857)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.onAsyncInflationFinished(StatusBar.java:1874)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.NotificationInflater$AsyncInflationTask.onAsyncInflationFinished(NotificationInflater.java:641)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.NotificationInflater.finishIfDone(NotificationInflater.java:460)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.NotificationInflater.-wrap0(Unknown Source:0)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.systemui.statusbar.notification.NotificationInflater$6.onViewApplied(NotificationInflater.java:343)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:3478)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:3458)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6809)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
02-24 16:50:54.994 10514 10514 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

```

**Comment by Trumeet** [comment]
我去撸一眼 SystemUI 的代码吧，看看怎么触发的

**Comment by TimothyZhang023** [comment]
我单步看 coolapk的，里面获取package里面那个miui_notification icon 拿到了resource id，，，然而解开包看了一下，里面并没有那个icon文件。。。所以后面设置notification 的small icon其实没有获取到icon，然后SystemUI 试图显示icon时候就bug了。。。
