### ISSUE TITLE
E/PushCore: get isMIUI failed

### ISSUE THREAD

**Issue by izhangzhihao** [Trumeet/MiPushFramework#77]
```
E/PushCore: get isMIUI failed
java.io.FileNotFoundException: /system/build.prop (Permission denied)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.getIsMIUI(Unknown Source:28)
	at com.xiaomi.channel.commonutils.android.MIUIUtils.isMIUI(Unknown Source:4)
	at com.xiaomi.channel.commonutils.android.DeviceInfo.quicklyGetIMEI(Unknown Source:8)
	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:642)
	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:7)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by Trumeet** [comment]
忽略即可。

**Comment by shuxinhuang** [comment]
您好。这个不能解决吗？还有一个问题 push service 的tag 是什么意思呢？谢谢
