### ISSUE TITLE
Buuuuuug

### ISSUE THREAD

**Issue by naloder** [Trumeet/MiPushFramework#82]
有时候点击推送过来的通知没反应。。打开不了对应app。
还有最近一次的重大bug的log
java.lang.NoSuchMethodError: No virtual method getPackageImportance(Ljava/lang/String;)I in class Landroid/app/ActivityManager; or its super classes (declaration of 'android.app.ActivityManager' appears in /system/framework/framework.jar)
	at top.trumeet.common.override.ActivityManagerOverride.getPackageImportance(ActivityManagerOverride.java:13)
	at com.xiaomi.push.sdk.MyPushMessageHandler.isAppForeground(MyPushMessageHandler.java:150)
	at com.xiaomi.push.sdk.MyPushMessageHandler.onHandleIntent(MyPushMessageHandler.java:72)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)

然后系统UI就豹炸了(

**Comment by TimothyZhang023** [comment]
系统版本提供一下

**Comment by naloder** [comment]
@TimothyZhang023 安卓5.1

**Comment by Trumeet** [comment]
Hidden api 不兼容的锅，我去看下 Lollipop 的代码

**Comment by naloder** [comment]
啥时候修(

**Comment by TimothyZhang023** [comment]
新版可以选择兼容模式。绕开这个问题
