### ISSUE TITLE
点击通知之后后端会崩溃

### ISSUE THREAD

**Issue by duoduoeeee** [Trumeet/MiPushFramework#85]
如题，网易云音乐的5.0.0.559922版，aosp 7.1.2，堆栈输出如下

java.lang.SecurityException: Permission Denial: getPackageProcessState from pid=22020, uid=10179 requires android.permission.GET_PACKAGE_IMPORTANCE
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.ActivityManagerProxy.getPackageProcessState(ActivityManagerNative.java:6800)
	at android.app.ActivityManager.getPackageImportance(ActivityManager.java:3085)
	at top.trumeet.common.override.ActivityManagerOverride.getPackageImportance(ActivityManagerOverride.java:13)
	at com.xiaomi.push.sdk.MyPushMessageHandler.isAppForeground(MyPushMessageHandler.java:150)
	at com.xiaomi.push.sdk.MyPushMessageHandler.onHandleIntent(MyPushMessageHandler.java:72)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

貌似是后端无法理解通知消息的优先级？推测和应用没申请到权限有关系

是最新的版本（a2b0fb2）和配套的后端manager。

其他貌似一切正常。

**Comment by TimothyZhang023** [comment]
猜测应该是  getPackageImportance 权限不够

理论上这个权限只能给system app使用，这里我们用反射调用了。但是可能被限制了，按照最新官方说明，后面会进一步禁止这种反射调用私有api的情况，或许是AOSP代码比较新，所以遇到了 这个限制。

如果说解决的，你可以尝试吧push 转换为系统应用试试

**Comment by Trumeet** [comment]
@TimothyZhang023 AOSP 应该没事的呀，我去看下，我这里 API 27 没事

**Comment by Trumeet** [comment]
http://androidxref.com/7.1.2_r36/xref/frameworks/base/services/core/java/com/android/server/am/ActivityManagerService.java#4109 
果真，在 7.1 上面是需要权限的，已确认 Bug

**Comment by Trumeet** [comment]
等一下... 忘了看到 http://androidxref.com/7.1.2_r36/xref/frameworks/base/services/core/java/com/android/server/am/ActivityManagerService.java#4108 上面会验证，没有 UsageStaus 权限才会要系统权限.. 抱歉疏忽了

**Comment by Trumeet** [comment]
请问您授予 Push “使用情况” 权限了吗？

**Comment by duoduoeeee** [comment]
将push转为系统应用 问题解决

**Comment by TimothyZhang023** [comment]
新增了兼容模式 。可以尝试一下  https://github.com/Trumeet/MiPushFramework/releases/tag/18bc05b-SNAPSHOT
